### PR TITLE
Fix getjson issues with plugin_opts

### PR DESCRIPTION
**Pull request by ytreister**
getjson worked fine when the options were in the configuration file, but failed when options were specified via plugin_opts. This was since Python does not store dictionaries with double quotes, and json.loads failed to properly process a string. I replaced with ast.lieral_eval and beefed up the tests to make sure it works for both config files and plugin_opts

### CODE REVIEW

**Comment by mlaferrera** [comment]
I'm a bit confused. Is there a reason it shouldn't fall inline with how the other helpers operate, similar to:

    def getjson(self, section, option, *args, **kwargs) -> Any:
        """
        Create a Python object from `ConfigParser` option using JSON syntax
        """
        value = self.get(section, option, fallback=kwargs.get('fallback', ''))
        if isinstance(value, (dict, list)):
            return value
        return json.loads(value)

**Comment by ytreister** [comment]
`json.loads()` does not work because of this code in `StoqPluginManager`:
```python
if self._plugin_opts.get(plugin_name):
            plugin_config.read_dict(
                {'options': self._plugin_opts[plugin_name]}  # type: ignore
            )
```
The type returned by `value = self.get(section, option, fallback=kwargs.get('fallback', '')` will always be a string.  Even if I define my plugin_opts json with double quotes, `read_dict` converts it to single quotes...

I added extra tests to make sure it works for all these situations...

**Comment by ytreister** [comment]
One of my big use cases for using json in configuration files is to make a nice dispatcher:
```ini
[options]
dispatch_rules = {
  "Archive": ["handle_archive"],
  "PE": ["metadefender", "peparser", "signsrch"],
  "OLE": ["olethis", "olethat"]
}
```
Another allows for nicer config files:
```ini
[options]
ignored_resource_types = [
	"RT_CURSOR",
	"RT_BITMAP",
	"RT_ICON",
	"RT_MENU",
	"RT_DIALOG",
	"RT_STRING",
	"RT_ACCELERATOR",
	"RT_GROUP_CURSOR",
	"RT_GROUP_ICON",
	"RT_VERSION",
	"RT_MANIFEST"
	]
```

**Comment by mlaferrera** [comment]
Thanks for the great feedback. I think we're definitely on the right track, especially considering your use case. I just ran your tests with the below code (which is how stoq handles it for the other helpers (`getlist`, `getset`)) and all of your tests pass, with one exception. I had to update the exception type to `json.decoder.JSONDecodeError` when testing for invalid JSON in `tests/test_helpers.py`. 

Considering this is a configuration option that could affect the overall scan results and it's handled upon plugin instantiation, I'd rather stoq not continue gracefully with a simple error message. So the below code does not attempt to catch any exceptions.

```
    def getjson(self, section, option, *args, **kwargs) -> Union[List, Dict]:
        """
        Create a Python object from `ConfigParser` option using JSON syntax
        """
        value = self.get(section, option, fallback=kwargs.get('fallback', {}))
        if isinstance(value, (dict, list)):
            return value
        return json.loads(value)
```

This also highlighted an issue in the `stoq` cli command where it is not properly parsing command line options that contain and `=` or `:` in the plugin option value. I've pushed up a fix for that (a8a1d7a), and will merge shortly.

Thanks again for the PR! If you can make the above changes I'll happily merge it.

**Comment by ytreister** [comment]
I made updates based on your feedback.  I am glad that my enhancement helped you find another defect.

Again,  `json.loads` can't be used because single quotes are used when read_dict converts the python dictionary to a string.  My tests are in `test_plugin_manager.py`, I removed the original tests from `test_helpers.py`.

**Comment by mlaferrera** [comment]
That won't be the case if you're loading the plugin options from a stoq config file or the command line using `--plugin-opts`. If you're passing it via `Stoq()`, (i.e., `s = Stoq(plugin_opts=...)`), the plugin options should already be the appropriate object type.

**Comment by ytreister** [comment]
I agree that json.loads could be used if the options are passed via command line or from config file, but when they get passed in via `Stoq(plugin_opts=...)` they get converted from the appropriate type to a string and when you pass that string to json.loads it fails because that string has single quotes which is not JSON.

**Comment by mlaferrera** [comment]
I see where the issue is. This is a bug that should be dealt with in the framework, not the helper since it affects more than just `getjson`.  I'll work on how to best handle that within the framework. Thanks for highlighting another edge case that helps to improve stoQ!

**Comment by ytreister** [comment]
OK sounds good, for now I will use my branch as a workaround...

**Comment by mlaferrera** [comment]
After digging into this deeper and talking with some colleagues, I don't believe using `ast.literal_eval` is the best path forward. `ConfigParser` values only support strings, and circumventing the intended use of it for one function (`getlist` and `getset` don't handle literals either) would add more confusion and complexity to do it right. To ensure that it works properly when calling `Stoq(plugin_opts=...)` you can simply pass a valid json blob, rather than a dict for the plugin option values.

In the long run, I think it may be a better option to work towards using a yaml/json style configuration file for plugins and stoQ. This will allow for much more complex configuration options than is currently available.

**Comment by ytreister** [comment]
OK, so are you saying that the recommended solution (for now) should be that for options which are retrieved via the getjson method we should make an exception and pass in plugin_opts as a JSON blob instead of a dictionary or a list?  Is there still a bug/issue with the framework?  If so, I can wait until you fix the bug and then update this branch...  Or you can take care of it.  Just let me know...

**Comment by mlaferrera** [comment]
Sorry, I don't think I worded by response well in that respect. Using your examples above, you can do something like this:

```
import json
from stoq import Stoq

dispatch_rules = {
    'Archive': ['handle_archive'],
    'PE': ['metadefender', 'peparser', 'signsrch'],
    'OLE': ['olethis', 'olethat'],
}

plugin_opts = {'yara': {'dispatch_rules': json.dumps(dispatch_rules)}}
s = Stoq(plugin_opts=plugin_opts, ...)
```

It's not a bug with the framework, more of a limitation for using `configparser`. We will look into what's needed to use yaml/json config files as well, which will pretty much correct this limitation. I'm not sure on timeline yet, though.

Do you mind updating your PR with the `json.loads` call rather than `ast.literal`? I'd like to ensure the commit remains credited to you and this makes it much easier for tracking purposed over time.

Thanks again!

**Comment by ytreister** [comment]
Will do

**Comment by ytreister** [comment]
I made the changes based on our discussions.  All tests pass.

**Comment by ytreister** [comment]
@mlaferrera Not sure it is high priority to alter the framework to support JSON/YAML.  The solution in this branch works well for me.  I would say that at least 50% of my plugins utilize configs with JSON and I am able to get in some pretty complicated nested data structures with no problem.  Maybe just need to update the docs to say that when doing `Stoq(plugin_opts=...)` that are "get" using the getjson helper, they should be entered like `json.dumps(option)`.  Also, since getjson supports both list and dict objects, do you think the framework should continue to have getlist?

**Comment by mlaferrera** [comment]
Thanks! I'll work on trying to get this merged this week. 

Yeah, `getlist` and `getset` are both currently used in plugins, and they also simply split comma delimited strings. They will remain for the foreseeable future.

**Pull request merged**
