### PR TITLE
Added version info class and logic to base class to include it

### PR DESCRIPTION
**Pull request by ytreister**
This is what we discussed in issue #122.  If this got merged as-is, you would be able to add 3rd party version information to plugins.

As an example, you could add something like this to the exif plugin:
```python
class ExifToolPlugin(WorkerPlugin):
    def __init__(self, config: StoqConfigParser) -> None:
        super().__init__(config)
        self.bin = config.get('options', 'bin', fallback='exiftool')
        # Get and add exiftool version information
        output = run([self.bin, '-ver'], stdout=PIPE)
        version = output.stdout.rstrip()
        self.version_info.add_extra_version_info({'ExifToolVersion': version})
```
Other plugins could have more complex version info.  For example OPSWAT Metadefender could have last definition update times for each scanner in addition to the version of Metadefender used.

### CODE REVIEW

**Comment by mlaferrera** [comment]
Thanks for this PR as well, @ytreister! I'm going to take a deeper dive into this one just to make sure nothing unexpected breaks. This looks like a great way to implement your concept. I'll hopefully be able to get through testing it quickly.

**Comment by ytreister** [comment]
@mlaferrera Any more thoughts on this one?

Here is screenshot of debugging my decorated response (note: this is my codebase before this PR, just trying to show you how it is nice to know which version of 3rd party tools, etc.)
image

And here is how my decorator got the result (this is also before the PR, would adjust accordingly)
image

**Comment by mlaferrera** [comment]
Hi @ytreister -- I haven't forgotten. I have this on my list of things to do this week.

**Comment by mlaferrera** [comment]
Hi @ytreister -- thanks again for this PR! I've made a few changes that are inline with how we normally handle things within stoQ, and also added a test for invalid plugin version info.

Can you also please add a section in `docs/dev/plugin_overview.rst` that provides documentation on how to use this feature?

With that, are you expecting the plugin to add plugin version info itself to the results from stoQ? Or, are you hoping that the framework automatically adds it for each plugin? Based on this PR, I'm assuming it is the former?

**Comment by ytreister** [comment]
The way I use it is I have a decorator that will only query for version_info for the workers that were run.  I am not sure it makes sense to provide version info in the results automatically, because some stoQ users may not care about it.  Will work on documentation...

**Comment by ytreister** [comment]
@mlaferrera I added documentation but I am unsure of how to preview it in non markup format.

**Comment by ytreister** [comment]
I figured out how to view the markup from github, just not using the readthedocs page.  I was debating how much detail to go into, please let me know what your thoughts are.  I could add a scan method which appends `self.version_info` in the `WorkerResponse`.  I could create a sample Decorator class which loops over plugins_run, this is what that might look like:
```python
from stoq.plugins import DecoratorPlugin
from stoq import StoqResponse, DecoratorResponse
class VersionInfoPlugin(DecoratorPlugin):
	async def decorate(self, response: StoqResponse) -> DecoratorResponse:
		'''
		Returns Decorator with version information of each plugin that run during the scan
		'''
		version_info = {}

		# Get set of all workers that ran during the scan
		workers = set()
		for result in response.results:
			workers.update(result.plugins_run.get('workers'))

		# Add version_info for each worker
		s = Stoq()
		for worker in workers:
			version_info.update({worker: s.load_plugin(worker).version_info.__})
		return DecoratorResponse(version_info)
```

I am open to any ideas...

**Comment by mlaferrera** [comment]
@ytreister I think this may be a better fit to have as part of the `WorkerResponse` object, as you mentioned. That way a decorator could easily iterate over `Request` for the `WorkerResponse` objects and parse out the version information as needed.

**Comment by ytreister** [comment]
@mlaferrera I am not sure what the next steps should be to get this feature ready for merge...

**Comment by mlaferrera** [comment]
I just pushed up a commit with the changes I was thinking, but I'm not 100% sure this is the best way to go either. More work needs to be done to figure out the best way to get the `version_info` results to other plugins, without guaranteeing they will be in the `StoqResponse` object.

**Comment by ytreister** [comment]
Now that I see what you have implemented, I think I prefer my decorator that collects version info as I showed in my demo code above.  There are pros and cons to both ideas, but I think mine is much more simple in the end.
**Version Info in base class**
_PROS_
- If no 3rd party info needed, there is no extra work to do
- Can add 3rd party version info in the constructor, so this only needs to occur one time.
- Do not have to define version_info for each payload the worker scans
_CONS_
- For version_info that changes often (example: Metadefender definition update times), it is possible that the version_info collected during decoration is different then when scan occurred
**Version Info in worker response**
_PROS_
- Version_info can be super accurate and change from scan to scan
_CONS_
- Extra work for user to add version_info to worker response.  Especially when no 3rd party info is needed.  This leads to bloated worker code...
- Too much info for a user to digest from a WorkerResponse object.  Imagine a StoqResponse where we have lets say 100 payloads, that all ran exif.py, we would receive 100 version_info objects.  With my other proposed method we would just loop over all plugins_run and get a single list of workers run on all payloads and then could get the version_info for each...

**Comment by ytreister** [comment]
@mlaferrera This is what I prefer...
> I figured out how to view the markup from github, just not using the readthedocs page. I was debating how much detail to go into, please let me know what your thoughts are. I could add a scan method which appends `self.version_info` in the `WorkerResponse`. I could create a sample Decorator class which loops over plugins_run, this is what that might look like:
> 
> ```python
> from stoq.plugins import DecoratorPlugin
> from stoq import StoqResponse, DecoratorResponse
> class VersionInfoPlugin(DecoratorPlugin):
> 	async def decorate(self, response: StoqResponse) -> DecoratorResponse:
> 		'''
> 		Returns Decorator with version information of each plugin that run during the scan
> 		'''
> 		version_info = {}
> 
> 		# Get set of all workers that ran during the scan
> 		workers = set()
> 		for result in response.results:
> 			workers.update(result.plugins_run.get('workers'))
> 
> 		# Add version_info for each worker
> 		s = Stoq()
> 		for worker in workers:
> 			version_info.update({worker: s.load_plugin(worker).version_info.__})
> 		return DecoratorResponse(version_info)
> ```
> 
> I am open to any ideas...

**Comment by mlaferrera** [comment]
All valid points. If version info is instantiated in the base class, then it should not be modified by the plugin after instantiation. Otherwise, version info will become inconsistent and inaccurate with each run/modification.

Another problem is making the results available to decorators and/or connectors. This means the `VersionInfo` objects must be stored in `StoqResponse`, without requiring the version information in each result. 

If you'd like to work on that, please do. Otherwise I'm hoping to spend more time on this in a couple of weeks. Unfortunately right now my time is consumed on another project.

**Comment by ytreister** [comment]
I agree with you.  I think it can wait...

**Comment by ytreister** [comment]
Now that I am starting to make my plugins use aiohttp for requests and asyncio.subprocess, I am now wondering if I should force version_info methods to be async.  Otherwise, I have for example exif, a async subprocess for calling exiftool, but for getting the version info a non-async subprocess call.  I end up having to 
```python
from subprocess import ...
from asyncio.suvprocess import ...
```
and I think I would prefer to only have to import the async version which would look cleaner.

**Comment by ytreister** [comment]
There are two types of version_info, ones that can change from scan to scan, and ones that only change when using a new instance.  For example, my opswat version_info changes very often since AV definitions get updated on my system very often, however my exif version_info only changes if I update my plugin or version of exiftool.  Since I call opswat via an API, I have no control over when OPSWAT updates.  I have control over exiftool updates.

I propose version_info being optional part of the stoq response.  A decorator can gather the version_info and do what it likes with it.  It can either gather it by inspecting the stoq responses and/or it can call the version_info method for all plugins that were run.

**Comment by ytreister** [comment]
This is a little complicated, so closed the issue.

**Pull request closed without merging**
